# Generated by Django 4.2.5 on 2023-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
